### ISSUE TITLE
NoMethodError at /

### ISSUE THREAD

**Issue by captn3m0** [alagu/pagoda#8]
Sorry about posting it here, but I'm not that familiar with rails to fix it myself.

Running Ruby `v1.9.3-preview1`.

```
/home/nemo/.rvm/rubies/ruby-1.9.3-preview1/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:45:in `require': iconv will be deprecated in the future, use String#encode instead.
[2013-06-07 15:14:24] INFO  WEBrick 1.3.1
[2013-06-07 15:14:24] INFO  ruby 1.9.3 (2011-07-31) [x86_64-linux]
== Sinatra/1.4.2 has taken the stage on 4567 for development with backup from WEBrick
[2013-06-07 15:14:24] INFO  WEBrick::HTTPServer#start: pid=30898 port=4567
Configuration from ./_config.yml
NoMethodError - undefined method `name' for <Post: /blog/2009/11/19/welcome>:Jekyll::Post:
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/pagoda-jekyll-0.0.9/lib/pagoda/helper.rb:49:in `block in posts_template_data'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/pagoda-jekyll-0.0.9/lib/pagoda/helper.rb:46:in `map'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/pagoda-jekyll-0.0.9/lib/pagoda/helper.rb:46:in `posts_template_data'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/pagoda-jekyll-0.0.9/lib/pagoda/app.rb:76:in `block in <class:App>'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1415:in `call'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1415:in `block in compile!'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:944:in `[]'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:944:in `block (3 levels) in route!'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:960:in `route_eval'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:944:in `block (2 levels) in route!'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:981:in `block in process_route'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:979:in `catch'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:979:in `process_route'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:943:in `block in route!'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:942:in `each'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:942:in `route!'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1053:in `block in dispatch!'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1035:in `block in invoke'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1035:in `catch'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1035:in `invoke'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1050:in `dispatch!'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:878:in `block in call!'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1035:in `block in invoke'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1035:in `catch'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1035:in `invoke'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:878:in `call!'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:864:in `call'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/rack-protection-1.5.0/lib/rack/protection/xss_header.rb:18:in `call'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/rack-protection-1.5.0/lib/rack/protection/path_traversal.rb:16:in `call'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/rack-protection-1.5.0/lib/rack/protection/json_csrf.rb:18:in `call'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/rack-protection-1.5.0/lib/rack/protection/base.rb:49:in `call'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/rack-protection-1.5.0/lib/rack/protection/base.rb:49:in `call'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/rack-protection-1.5.0/lib/rack/protection/frame_options.rb:31:in `call'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/showexceptions.rb:21:in `call'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:172:in `call'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1947:in `call'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1610:in `block in call'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1693:in `synchronize'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1610:in `call'
        /home/nemo/.rvm/gems/ruby-1.9.3-preview1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
        /home/nemo/.rvm/rubies/ruby-1.9.3-preview1/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
        /home/nemo/.rvm/rubies/ruby-1.9.3-preview1/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
        /home/nemo/.rvm/rubies/ruby-1.9.3-preview1/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
localhost - - [07/Jun/2013:15:14:46 IST] "GET / HTTP/1.1" 500 132083

```

**Comment by captn3m0** [comment]
I'm running pagoda against [this repo](https://github.com/captn3m0/captn3m0.github.com)

**Comment by captn3m0** [comment]
Upgraded Ruby using rvm to ruby 1.9.3p429 (2013-05-15 revision 40747) [x86_64-linux]. Still facing the same error.

**Comment by alagu** [comment]
Hello, sorry for the bug. I'll have a look at this issue.

**Comment by alagu** [comment]
Which Jekyll version do you use?

**Comment by alagu** [comment]
There seems to be a similar issue here - https://github.com/mojombo/jekyll/issues/527

**Comment by captn3m0** [comment]
Yup, that was it. I was running an ancient jekyll. Upgraded to 1.0.3 and it works now.

Thanks!

**Comment by alagu** [comment]
Cool :-)
—

**Comment by alagu** [comment]
Hey, just wanted to check - you are using Jekyll 1.0.3 and Pagoda works without any issue?

**Comment by captn3m0** [comment]
I'm getting 404s on the "View" links, but rest all works perfectly.

**Comment by gms8994** [comment]
Same as @captn3m0

**Comment by alagu** [comment]
The View links are still not functional. So it is a valid bug.

@gms8994, do you have the same "View" links bug or the previously reported one?
